//===----------------------------------------------------------------------===//
//
// This source file is part of the swift-libgit2 open source project.
//
// Copyright (c) Margins Technologies LLC.
// Licensed under the Apache License, Version 2.0.
//
//===----------------------------------------------------------------------===//

import CLibgit2



/// These enums specify additional protocols beyond ``CEnum`` for
/// documentation purposes.
///
/// Enums that can use a simple raw value type get automatic `Equatable`,
/// `Hashable`, and `RawRepresentable` conformance, which DocC automatically
/// documents. However, these enums implement `RawRepresentable` manually to
/// support an unknown case with an associated value, which prevents automatic
/// conformance.
///
/// Explicitly declaring `Equatable`, `Hashable`, and `RawRepresentable`
/// conformance ensures that DocC includes these protocol implementations in
/// the generated documentation, maintaining consistency with the documentation
/// of other enums.



/// Operation result codes.
///
/// Despite its name, this enum represents both success and error codes.
/// The ``GitErrorCode/gitOK`` case indicates a successful operation, while
/// all other cases represent various error conditions.
///
/// Some libgit2 functions also return non-zero values from caller-provided
/// callbacks. These callback return values will be wrapped in the
/// ``GitErrorCode/gitUnknown(_:)`` case.
///
/// ## C Equivalent
///
/// [`git_error_code`](https://libgit2.org/docs/reference/main/errors/git_error_code.html)
public enum GitErrorCode: CEnum, Equatable, Hashable, RawRepresentable
{
    /// No error occurred, and the operation was successful.
    case gitOK
    
    /// An error occurred.
    ///
    /// Callers should call ``gitErrorLast()`` for more information.
    case gitError
    
    /// The requested object could not be found.
    case gitENotFound
    
    /// The object already exists, preventing the operation.
    case gitEExists
    
    /// More than one object matches the query.
    case gitEAmbiguous
    
    /// The output buffer is too short to hold the data.
    case gitEBufs
    
    /// A special error that is never generated by libgit2.
    ///
    /// Callers may return this error from a callback to know that it was
    /// generated by the callback and not by libgit2.
    ///
    /// - Important: swift-libgit2 functions will return this error code if
    /// a parameter could not be converted from Swift to C, or in other cases
    /// specific to individual functions.
    case gitEUser
    
    /// The operation is not allowed on a bare repository.
    case gitEBareRepo
    
    /// HEAD refers to a branch with no commits.
    case gitEUnbornBranch
    
    /// An in-progress merge prevented the operation.
    case gitEUnmerged
    
    /// The reference is not fast-forwardable.
    case gitENonFastForward
    
    /// The name or refspec is not valid.
    case gitEInvalidSpec
    
    /// A checkout conflict prevented the operation.
    case gitEConflict
    
    /// A locked file prevented the operation.
    case gitELocked
    
    /// The reference value does not match the expected value.
    case gitEModified
    
    /// An authentication error occurred.
    case gitEAuth
    
    /// The server certificate is invalid.
    case gitECertificate
    
    /// The patch or merge has already been applied.
    case gitEApplied
    
    /// The requested peel operation is not possible.
    case gitEPeel
    
    /// An unexpected EOF was encountered.
    case gitEEOF
    
    /// An invalid operation or input occurred.
    case gitEInvalid
    
    /// Uncommitted changes in the index prevented the operation.
    case gitEUncommitted
    
    /// The operation is not valid for a directory.
    case gitEDirectory
    
    /// A merge conflict exists and cannot continue.
    case gitEMergeConflict
    
    /// A callback refused to act.
    case gitPassthrough
    
    /// Iteration is over.
    case gitIterOver
    
    /// An internal libgit2 result code.
    case gitRetry
    
    /// An object hashsum mismatch occurred.
    case gitEMismatch
    
    /// The operation would overwrite unsaved changes in the index.
    case gitEIndexDirty
    
    /// The patch application failed.
    case gitEApplyFail
    
    /// The object is not owned by the current user.
    case gitEOwner
    
    /// The operation timed out.
    case gitTimeout
    
    /// There were no changes.
    case gitEUnchanged
    
    /// An option is not supported.
    case gitENotSupported
    
    /// The subject is read-only.
    case gitEReadOnly
    
    /// An unknown or undocumented libgit2 result code.
    case gitUnknown(Int32)
    
    
    
    /// Initializes a ``GitErrorCode`` instance from the given raw value.
    /// - Parameter rawValue: The raw value to use.
    public init(
        rawValue: Int32
    )
    {
        switch rawValue
        {
            case 0      : self = .gitOK
            case -1     : self = .gitError
            case -3     : self = .gitENotFound
            case -4     : self = .gitEExists
            case -5     : self = .gitEAmbiguous
            case -6     : self = .gitEBufs
            case -7     : self = .gitEUser
            case -8     : self = .gitEBareRepo
            case -9     : self = .gitEUnbornBranch
            case -10    : self = .gitEUnmerged
            case -11    : self = .gitENonFastForward
            case -12    : self = .gitEInvalidSpec
            case -13    : self = .gitEConflict
            case -14    : self = .gitELocked
            case -15    : self = .gitEModified
            case -16    : self = .gitEAuth
            case -17    : self = .gitECertificate
            case -18    : self = .gitEApplied
            case -19    : self = .gitEPeel
            case -20    : self = .gitEEOF
            case -21    : self = .gitEInvalid
            case -22    : self = .gitEUncommitted
            case -23    : self = .gitEDirectory
            case -24    : self = .gitEMergeConflict
            case -30    : self = .gitPassthrough
            case -31    : self = .gitIterOver
            case -32    : self = .gitRetry
            case -33    : self = .gitEMismatch
            case -34    : self = .gitEIndexDirty
            case -35    : self = .gitEApplyFail
            case -36    : self = .gitEOwner
            case -37    : self = .gitTimeout
            case -38    : self = .gitEUnchanged
            case -39    : self = .gitENotSupported
            case -40    : self = .gitEReadOnly
            default     : self = .gitUnknown(rawValue)
        }
    }
    
    
    
    /// The raw value.
    public var rawValue: Int32
    {
        switch self
        {
            case .gitOK                 : return 0
            case .gitError              : return -1
            case .gitENotFound          : return -3
            case .gitEExists            : return -4
            case .gitEAmbiguous         : return -5
            case .gitEBufs              : return -6
            case .gitEUser              : return -7
            case .gitEBareRepo          : return -8
            case .gitEUnbornBranch      : return -9
            case .gitEUnmerged          : return -10
            case .gitENonFastForward    : return -11
            case .gitEInvalidSpec       : return -12
            case .gitEConflict          : return -13
            case .gitELocked            : return -14
            case .gitEModified          : return -15
            case .gitEAuth              : return -16
            case .gitECertificate       : return -17
            case .gitEApplied           : return -18
            case .gitEPeel              : return -19
            case .gitEEOF               : return -20
            case .gitEInvalid           : return -21
            case .gitEUncommitted       : return -22
            case .gitEDirectory         : return -23
            case .gitEMergeConflict     : return -24
            case .gitPassthrough        : return -30
            case .gitIterOver           : return -31
            case .gitRetry              : return -32
            case .gitEMismatch          : return -33
            case .gitEIndexDirty        : return -34
            case .gitEApplyFail         : return -35
            case .gitEOwner             : return -36
            case .gitTimeout            : return -37
            case .gitEUnchanged         : return -38
            case .gitENotSupported      : return -39
            case .gitEReadOnly          : return -40
            case .gitUnknown(let code)  : return code
        }
    }
    
    
    
    /// Initializes a ``GitErrorCode`` instance from the given `git_error_code`
    /// instance.
    /// - Parameter error: The `git_error_code` instance to use.
    internal init?(
        cValue error: git_error_code
    )
    {
        switch error
        {
            case GIT_OK                 : self = .gitOK
            case GIT_ERROR              : self = .gitError
            case GIT_ENOTFOUND          : self = .gitENotFound
            case GIT_EEXISTS            : self = .gitEExists
            case GIT_EAMBIGUOUS         : self = .gitEAmbiguous
            case GIT_EBUFS              : self = .gitEBufs
            case GIT_EUSER              : self = .gitEUser
            case GIT_EBAREREPO          : self = .gitEBareRepo
            case GIT_EUNBORNBRANCH      : self = .gitEUnbornBranch
            case GIT_EUNMERGED          : self = .gitEUnmerged
            case GIT_ENONFASTFORWARD    : self = .gitENonFastForward
            case GIT_EINVALIDSPEC       : self = .gitEInvalidSpec
            case GIT_ECONFLICT          : self = .gitEConflict
            case GIT_ELOCKED            : self = .gitELocked
            case GIT_EMODIFIED          : self = .gitEModified
            case GIT_EAUTH              : self = .gitEAuth
            case GIT_ECERTIFICATE       : self = .gitECertificate
            case GIT_EAPPLIED           : self = .gitEApplied
            case GIT_EPEEL              : self = .gitEPeel
            case GIT_EEOF               : self = .gitEEOF
            case GIT_EINVALID           : self = .gitEInvalid
            case GIT_EUNCOMMITTED       : self = .gitEUncommitted
            case GIT_EDIRECTORY         : self = .gitEDirectory
            case GIT_EMERGECONFLICT     : self = .gitEMergeConflict
            case GIT_PASSTHROUGH        : self = .gitPassthrough
            case GIT_ITEROVER           : self = .gitIterOver
            case GIT_RETRY              : self = .gitRetry
            case GIT_EMISMATCH          : self = .gitEMismatch
            case GIT_EINDEXDIRTY        : self = .gitEIndexDirty
            case GIT_EAPPLYFAIL         : self = .gitEApplyFail
            case GIT_EOWNER             : self = .gitEOwner
            case GIT_TIMEOUT            : self = .gitTimeout
            case GIT_EUNCHANGED         : self = .gitEUnchanged
            case GIT_ENOTSUPPORTED      : self = .gitENotSupported
            case GIT_EREADONLY          : self = .gitEReadOnly
            default                     : return nil
        }
    }
    
    
    
    /// Converts the ``GitErrorCode`` instance into a `git_error_code` instance.
    ///
    /// This method returns `GIT_EUSER` for the ``GitErrorCode/gitUnknown(_:)``
    /// case.
    ///
    /// The ``CEnum`` protocol requires conformance to ``CConvertible``,
    /// which requires a non-throwing conversion method. An alternative design
    /// would be to not conform to ``CEnum``, and instead directly conform to
    /// ``ThrowingCConvertible`` and the other necessary protocols, allowing
    /// this method to throw an error for unknown result codes.
    ///
    /// However, any thrown error would be caught by ``withCConversion(_:)``
    /// and converted to `GIT_EUSER` anyway, making the throwing variant
    /// functionally equivalent to the non-throwing variant, while creating
    /// unnecessary inconsistency with other enums.
    ///
    /// - Returns: The `git_error_code` instance.
    internal func cValue() -> git_error_code
    {
        switch self
        {
            case .gitOK                 : return GIT_OK
            case .gitError              : return GIT_ERROR
            case .gitENotFound          : return GIT_ENOTFOUND
            case .gitEExists            : return GIT_EEXISTS
            case .gitEAmbiguous         : return GIT_EAMBIGUOUS
            case .gitEBufs              : return GIT_EBUFS
            case .gitEUser              : return GIT_EUSER
            case .gitEBareRepo          : return GIT_EBAREREPO
            case .gitEUnbornBranch      : return GIT_EUNBORNBRANCH
            case .gitEUnmerged          : return GIT_EUNMERGED
            case .gitENonFastForward    : return GIT_ENONFASTFORWARD
            case .gitEInvalidSpec       : return GIT_EINVALIDSPEC
            case .gitEConflict          : return GIT_ECONFLICT
            case .gitELocked            : return GIT_ELOCKED
            case .gitEModified          : return GIT_EMODIFIED
            case .gitEAuth              : return GIT_EAUTH
            case .gitECertificate       : return GIT_ECERTIFICATE
            case .gitEApplied           : return GIT_EAPPLIED
            case .gitEPeel              : return GIT_EPEEL
            case .gitEEOF               : return GIT_EEOF
            case .gitEInvalid           : return GIT_EINVALID
            case .gitEUncommitted       : return GIT_EUNCOMMITTED
            case .gitEDirectory         : return GIT_EDIRECTORY
            case .gitEMergeConflict     : return GIT_EMERGECONFLICT
            case .gitPassthrough        : return GIT_PASSTHROUGH
            case .gitIterOver           : return GIT_ITEROVER
            case .gitRetry              : return GIT_RETRY
            case .gitEMismatch          : return GIT_EMISMATCH
            case .gitEIndexDirty        : return GIT_EINDEXDIRTY
            case .gitEApplyFail         : return GIT_EAPPLYFAIL
            case .gitEOwner             : return GIT_EOWNER
            case .gitTimeout            : return GIT_TIMEOUT
            case .gitEUnchanged         : return GIT_EUNCHANGED
            case .gitENotSupported      : return GIT_ENOTSUPPORTED
            case .gitEReadOnly          : return GIT_EREADONLY
            default                     : return GIT_EUSER
        }
    }
}



/// The category of an error.
///
/// ## C Equivalent
///
/// [`git_error_t`](https://libgit2.org/docs/reference/main/errors/git_error_t.html)
public enum GitErrorT: CEnum, Equatable, Hashable, RawRepresentable
{
    /// No error occurred, and the operation was successful.
    case gitErrorNone
    
    /// The error is related to lack of memory.
    case gitErrorNoMemory
    
    /// The error is related to the operating system.
    case gitErrorOS
    
    /// The error is related to an invalid operation or input.
    case gitErrorInvalid
    
    /// The error is related to a reference.
    case gitErrorReference
    
    /// The error is related to ZLib.
    case gitErrorZLib
    
    /// The error is related to the repository.
    case gitErrorRepository
    
    /// The error is related to the configuration.
    case gitErrorConfig
    
    /// The error is related to a regular expression.
    case gitErrorRegex
    
    /// The error is related to the object database.
    case gitErrorODB
    
    /// The error is related to the index.
    case gitErrorIndex
    
    /// The error is related to an object.
    case gitErrorObject
    
    /// The error is related to a network operation.
    case gitErrorNet
    
    /// The error is related to a tag.
    case gitErrorTag
    
    /// The error is related to a tree.
    case gitErrorTree
    
    /// The error is related to an indexer.
    case gitErrorIndexer
    
    /// The error is related to SSL.
    case gitErrorSSL
    
    /// The error is related to a submodule.
    case gitErrorSubmodule
    
    /// The error is related to a thread.
    case gitErrorThread
    
    /// The error is related to a stash.
    case gitErrorStash
    
    /// The error is related to a checkout operation.
    case gitErrorCheckout
    
    /// The error is related to `FETCH_HEAD`.
    case gitErrorFETCHHEAD
    
    /// The error is related to a merge operation.
    case gitErrorMerge
    
    /// The error is related to SSH.
    case gitErrorSSH
    
    /// The error is related to filtering.
    case gitErrorFilter
    
    /// The error is related to a revert operation.
    case gitErrorRevert
    
    /// The error is related to a callback.
    case gitErrorCallback
    
    /// The error is related to a cherrypick operation.
    case gitErrorCherrypick
    
    /// The error is related to a describe operation.
    case gitErrorDescribe
    
    /// The error is related to a rebase operation.
    case gitErrorRebase
    
    /// The error is related to the file system.
    case gitErrorFileSystem
    
    /// The error is related to a patch operation.
    case gitErrorPatch
    
    /// The error is related to a worktree.
    case gitErrorWorktree
    
    /// The error is related to a SHA ID.
    case gitErrorSHA
    
    /// The error is related to HTTP.
    case gitErrorHTTP
    
    /// The error is an internal error.
    case gitErrorInternal
    
    /// The error is related to a graft operation.
    case gitErrorGrafts
    
    /// An unknown or undocumented libgit2 result code.
    case gitUnknown(Int32)
    
    
    
    
    /// Initializes a ``GitError`` instance from the given raw value.
    /// - Parameter rawValue: The raw value to use.
    public init(
        rawValue: Int32
    )
    {
        switch rawValue
        {
            case 0  : self = .gitErrorNone
            case 1  : self = .gitErrorNoMemory
            case 2  : self = .gitErrorOS
            case 3  : self = .gitErrorInvalid
            case 4  : self = .gitErrorReference
            case 5  : self = .gitErrorZLib
            case 6  : self = .gitErrorRepository
            case 7  : self = .gitErrorConfig
            case 8  : self = .gitErrorRegex
            case 9  : self = .gitErrorODB
            case 10 : self = .gitErrorIndex
            case 11 : self = .gitErrorObject
            case 12 : self = .gitErrorNet
            case 13 : self = .gitErrorTag
            case 14 : self = .gitErrorTree
            case 15 : self = .gitErrorIndexer
            case 16 : self = .gitErrorSSL
            case 17 : self = .gitErrorSubmodule
            case 18 : self = .gitErrorThread
            case 19 : self = .gitErrorStash
            case 20 : self = .gitErrorCheckout
            case 21 : self = .gitErrorFETCHHEAD
            case 22 : self = .gitErrorMerge
            case 23 : self = .gitErrorSSH
            case 24 : self = .gitErrorFilter
            case 25 : self = .gitErrorRevert
            case 26 : self = .gitErrorCallback
            case 27 : self = .gitErrorCherrypick
            case 28 : self = .gitErrorDescribe
            case 29 : self = .gitErrorRebase
            case 30 : self = .gitErrorFileSystem
            case 31 : self = .gitErrorPatch
            case 32 : self = .gitErrorWorktree
            case 33 : self = .gitErrorSHA
            case 34 : self = .gitErrorHTTP
            case 35 : self = .gitErrorInternal
            case 36 : self = .gitErrorGrafts
            default : self = .gitUnknown(rawValue)
        }
    }
    
    
    
    /// The raw value.
    public var rawValue: Int32
    {
        switch self
        {
            case .gitErrorNone          : return 0
            case .gitErrorNoMemory      : return 1
            case .gitErrorOS            : return 2
            case .gitErrorInvalid       : return 3
            case .gitErrorReference     : return 4
            case .gitErrorZLib          : return 5
            case .gitErrorRepository    : return 6
            case .gitErrorConfig        : return 7
            case .gitErrorRegex         : return 8
            case .gitErrorODB           : return 9
            case .gitErrorIndex         : return 10
            case .gitErrorObject        : return 11
            case .gitErrorNet           : return 12
            case .gitErrorTag           : return 13
            case .gitErrorTree          : return 14
            case .gitErrorIndexer       : return 15
            case .gitErrorSSL           : return 16
            case .gitErrorSubmodule     : return 17
            case .gitErrorThread        : return 18
            case .gitErrorStash         : return 19
            case .gitErrorCheckout      : return 20
            case .gitErrorFETCHHEAD     : return 21
            case .gitErrorMerge         : return 22
            case .gitErrorSSH           : return 23
            case .gitErrorFilter        : return 24
            case .gitErrorRevert        : return 25
            case .gitErrorCallback      : return 26
            case .gitErrorCherrypick    : return 27
            case .gitErrorDescribe      : return 28
            case .gitErrorRebase        : return 29
            case .gitErrorFileSystem    : return 30
            case .gitErrorPatch         : return 31
            case .gitErrorWorktree      : return 32
            case .gitErrorSHA           : return 33
            case .gitErrorHTTP          : return 34
            case .gitErrorInternal      : return 35
            case .gitErrorGrafts        : return 36
            case .gitUnknown(let code)  : return code
        }
    }
    
    
    
    /// Initializes a ``GitErrorT`` instance from the given `git_error_t`
    /// instance.
    /// - Parameter error: The `git_error_t` instance to use.
    internal init?(
        cValue error: git_error_t
    )
    {
        switch error
        {
            case GIT_ERROR_NONE         : self = .gitErrorNone
            case GIT_ERROR_NOMEMORY     : self = .gitErrorNoMemory
            case GIT_ERROR_OS           : self = .gitErrorOS
            case GIT_ERROR_INVALID      : self = .gitErrorInvalid
            case GIT_ERROR_REFERENCE    : self = .gitErrorReference
            case GIT_ERROR_ZLIB         : self = .gitErrorZLib
            case GIT_ERROR_REPOSITORY   : self = .gitErrorRepository
            case GIT_ERROR_CONFIG       : self = .gitErrorConfig
            case GIT_ERROR_REGEX        : self = .gitErrorRegex
            case GIT_ERROR_ODB          : self = .gitErrorODB
            case GIT_ERROR_INDEX        : self = .gitErrorIndex
            case GIT_ERROR_OBJECT       : self = .gitErrorObject
            case GIT_ERROR_NET          : self = .gitErrorNet
            case GIT_ERROR_TAG          : self = .gitErrorTag
            case GIT_ERROR_TREE         : self = .gitErrorTree
            case GIT_ERROR_INDEXER      : self = .gitErrorIndexer
            case GIT_ERROR_SSL          : self = .gitErrorSSL
            case GIT_ERROR_SUBMODULE    : self = .gitErrorSubmodule
            case GIT_ERROR_THREAD       : self = .gitErrorThread
            case GIT_ERROR_STASH        : self = .gitErrorStash
            case GIT_ERROR_CHECKOUT     : self = .gitErrorCheckout
            case GIT_ERROR_FETCHHEAD    : self = .gitErrorFETCHHEAD
            case GIT_ERROR_MERGE        : self = .gitErrorMerge
            case GIT_ERROR_SSH          : self = .gitErrorSSH
            case GIT_ERROR_FILTER       : self = .gitErrorFilter
            case GIT_ERROR_REVERT       : self = .gitErrorRevert
            case GIT_ERROR_CALLBACK     : self = .gitErrorCallback
            case GIT_ERROR_CHERRYPICK   : self = .gitErrorCherrypick
            case GIT_ERROR_DESCRIBE     : self = .gitErrorDescribe
            case GIT_ERROR_REBASE       : self = .gitErrorRebase
            case GIT_ERROR_FILESYSTEM   : self = .gitErrorFileSystem
            case GIT_ERROR_PATCH        : self = .gitErrorPatch
            case GIT_ERROR_WORKTREE     : self = .gitErrorWorktree
            case GIT_ERROR_SHA          : self = .gitErrorSHA
            case GIT_ERROR_HTTP         : self = .gitErrorHTTP
            case GIT_ERROR_INTERNAL     : self = .gitErrorInternal
            case GIT_ERROR_GRAFTS       : self = .gitErrorGrafts
            default                     : return nil
        }
    }
    
    
    
    /// Converts the ``GitErrorT`` instance into a `git_error_t` instance.
    ///
    /// - Note: See ``GitErrorCode/cValue()`` for more information on the
    /// `default` case.
    ///
    /// - Returns: The `git_error_t` instance.
    internal func cValue() -> git_error_t
    {
        switch self
        {
            case .gitErrorNone          : return GIT_ERROR_NONE
            case .gitErrorNoMemory      : return GIT_ERROR_NOMEMORY
            case .gitErrorOS            : return GIT_ERROR_OS
            case .gitErrorInvalid       : return GIT_ERROR_INVALID
            case .gitErrorReference     : return GIT_ERROR_REFERENCE
            case .gitErrorZLib          : return GIT_ERROR_ZLIB
            case .gitErrorRepository    : return GIT_ERROR_REPOSITORY
            case .gitErrorConfig        : return GIT_ERROR_CONFIG
            case .gitErrorRegex         : return GIT_ERROR_REGEX
            case .gitErrorODB           : return GIT_ERROR_ODB
            case .gitErrorIndex         : return GIT_ERROR_INDEX
            case .gitErrorObject        : return GIT_ERROR_OBJECT
            case .gitErrorNet           : return GIT_ERROR_NET
            case .gitErrorTag           : return GIT_ERROR_TAG
            case .gitErrorTree          : return GIT_ERROR_TREE
            case .gitErrorIndexer       : return GIT_ERROR_INDEXER
            case .gitErrorSSL           : return GIT_ERROR_SSL
            case .gitErrorSubmodule     : return GIT_ERROR_SUBMODULE
            case .gitErrorThread        : return GIT_ERROR_THREAD
            case .gitErrorStash         : return GIT_ERROR_STASH
            case .gitErrorCheckout      : return GIT_ERROR_CHECKOUT
            case .gitErrorFETCHHEAD     : return GIT_ERROR_FETCHHEAD
            case .gitErrorMerge         : return GIT_ERROR_MERGE
            case .gitErrorSSH           : return GIT_ERROR_SSH
            case .gitErrorFilter        : return GIT_ERROR_FILTER
            case .gitErrorRevert        : return GIT_ERROR_REVERT
            case .gitErrorCallback      : return GIT_ERROR_CALLBACK
            case .gitErrorCherrypick    : return GIT_ERROR_CHERRYPICK
            case .gitErrorDescribe      : return GIT_ERROR_DESCRIBE
            case .gitErrorRebase        : return GIT_ERROR_REBASE
            case .gitErrorFileSystem    : return GIT_ERROR_FILESYSTEM
            case .gitErrorPatch         : return GIT_ERROR_PATCH
            case .gitErrorWorktree      : return GIT_ERROR_WORKTREE
            case .gitErrorSHA           : return GIT_ERROR_SHA
            case .gitErrorHTTP          : return GIT_ERROR_HTTP
            case .gitErrorInternal      : return GIT_ERROR_INTERNAL
            case .gitErrorGrafts        : return GIT_ERROR_GRAFTS
            default                     : return GIT_ERROR_NONE
        }
    }
}
